### ISSUE TITLE
wireless config broken after update to 2.141

### ISSUE THREAD

**Issue by nilsbecker** [volumio/Volumio2#1154]
i just updated and cannot get a wireless connection anymore. (rpi3) ethernet works. 
when i use the web ui to activate wireless, i get the option to switch it on. 
after switching on and saving, no wireless networks are listed
after navigating away and back to the network settings page, the wireless is listed as off again.

i imagine the wireless config got overwritten/messed up in the update. what can i do to reset it?

**Comment by xipmix** [comment]
Are you able to send in some logs of what happens when you try switching on the wireless?
 * reboot
 * try to activate wireless in web ui
 * go to /dev page, press the 'send logs' button near the bottom

**Comment by macmpi** [comment]
@nilsbecker : can you try with a freshly imaged SD (preferred), or clear all user data with Web UI, and check if problem persists?

**Comment by nilsbecker** [comment]
hi, i am having problems with my isp right now. i will get back to you when i can.

**Comment by leafy7382** [comment]
I am running into similar issue.

1. Plug into wired, can configure wireless now and getting 72Mbps
2. Unplug wired without rebooting, wireless still works, retains the same IP.
3. Now, reboot without wired plugged in, wireless does not reconnect properly
4. Plugging the wired connection back in does not yield proper IP either, so there is no way to get a /dev log sorry

**Comment by macmpi** [comment]
@leafy7382 which device are you using, what are the network interfaces (built-in, dongles,...)?
Can you plug a monitor & keyboard to the devices so we can check things when there is no connection?

**Comment by volumio** [comment]
@macmpi I confirm that PI3's internal wireless is broken. Wireless works only if an external dongle is used. Could you investigate?

**Comment by macmpi** [comment]
Happy to help, but I do not have a Pi3: need to find someone who can share connection to one and try remotely...

Is it due to udev rules: does it work if `/etc/udev/rules.d/99-Volumio-net.rules` is removed (renamed without `.rules`)?

**Comment by macmpi** [comment]
Does the issue appear with newly re-imaged SD, or only with OTA update?

**Comment by volumio** [comment]
Newly flashed img. This one:
http://updates.volumio.org/pi/volumio/2.156/volumio-2.156-2017-05-03-pi.img.zip

Renaming 99-Volumio-net.rules does not help 

What device do you have for testing? I assumed you had a PI3 since you told it was tested...

**Comment by macmpi** [comment]
Yes tested on a Pi3 remotely with help of @chsims1, and another one.
As it does not seem to come from udev rule, maybe some recent firmware file changes could be a cause.
Can one try using firmware files (from `/boot`) from earlier working version (2.129 for instance)?

**Comment by volumio** [comment]
Sure, specifically which files am I looking for?

**Comment by macmpi** [comment]
*.elf *.dat *.bin

**Comment by macmpi** [comment]
Does `ifconfig` display coherent interface names?
Can one share a log saved onto SD under console when no connections is available?

**Comment by volumio** [comment]
Ifconfig shows no wlan0 . 
However something strange is going on here... Flashed previous image (2.111) and tried on 2 different pis to exclude hardware issues.... Same result: both modules loaded for bcrm, no wlan0.
Now, trying with a third pi which shows wlan0 but creates no hotspot...
I'll keep you posted...

Are there reports of broken wifi on PI3s?

**Comment by volumio** [comment]
More news on this:
- With my third PI3 now wifi works
- Still no hotspot is started on first boot, seems an issue with /bin/hotspot.sh
-Trying with an older version of /bin/hotspot.sh

**Comment by volumio** [comment]
Ok, after restoring old /bin/hotspot.sh this is what I get:

May 03 22:37:55 volumio kernel: brcmfmac: brcmf_do_escan: error (-52)
May 03 22:37:55 volumio kernel: brcmfmac: brcmf_cfg80211_scan: scan error (-52)
May 03 22:37:55 volumio volumio[1057]: An error occurred while scanning: Error: Command failed: sudo /sbin/iwlist wlan0 scan
May 03 22:37:55 volumio volumio[1057]: wlan0     Interface doesn't support scanning : Invalid exchange
May 03 22:37:55 volumio volumio[1057]: Cannot use regular scanning, forcing with ap-force
May 03 22:37:55 volumio sudo[1471]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iw dev wlan0 scan ap-force
May 03 22:37:55 volumio sudo[1471]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:37:57 volumio sudo[1471]: pam_unix(sudo:session): session closed for user root
May 03 22:37:57 volumio kernel: brcmfmac: brcmf_do_escan: error (-52)
May 03 22:37:57 volumio kernel: brcmfmac: brcmf_cfg80211_scan: scan error (-52)
May 03 22:37:57 volumio volumio[1057]: command failed: Invalid exchange (-52)
May 03 22:37:57 volumio volumio[1057]: Cannot use fallback scanning method: Error: Command failed: /usr/bin/sudo /sbin/iw dev wlan0 scan ap-force
May 03 22:37:57 volumio volumio[1057]: command failed: Invalid exchange (-52)
May 03 22:38:08 volumio volumio[1057]: info: CALLMETHOD: system_controller network saveHotspotSettings [object Object]
May 03 22:38:08 volumio volumio[1057]: info: CoreCommandRouter::executeOnPlugin: network , saveHotspotSettings
May 03 22:38:08 volumio sudo[1480]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/chmod 777 /etc/hostapd/hostapd-edimax.conf
May 03 22:38:08 volumio sudo[1480]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:38:08 volumio sudo[1482]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/chmod 777 /etc/hostapd/hostapd.conf
May 03 22:38:08 volumio sudo[1480]: pam_unix(sudo:session): session closed for user root
May 03 22:38:08 volumio sudo[1482]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:38:08 volumio sudo[1482]: pam_unix(sudo:session): session closed for user root
May 03 22:38:08 volumio volumio[1057]: info: Permissions for /etc/hostapd/hostapd-edimax.conf
May 03 22:38:08 volumio volumio[1057]: info: Permissions for /etc/hostapd/hostapd.conf
May 03 22:38:08 volumio sudo[1498]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl restart wireless.service
May 03 22:38:08 volumio sudo[1498]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:38:08 volumio systemd[1]: Starting Wireless Services...
May 03 22:38:08 volumio sudo[1504]: root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iw dev wlan0 set power_save off
May 03 22:38:08 volumio sudo[1504]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:38:08 volumio sudo[1504]: pam_unix(sudo:session): session closed for user root
May 03 22:38:08 volumio wireless.js[1513]: start
May 03 22:38:08 volumio wireless.js[1513]: Cleaning previous...
May 03 22:38:08 volumio systemd[1]: Stopping dhcpd.service...
May 03 22:38:08 volumio systemd[1]: Stopping Host and Network Name Lookups.
May 03 22:38:08 volumio systemd[1]: Stopped target Host and Network Name Lookups.
May 03 22:38:08 volumio systemd[1]: Stopping dnsmasq.service...
May 03 22:38:08 volumio dnsmasq[1052]: exiting on receipt of SIGTERM
May 03 22:38:08 volumio systemd[1]: Stopped dnsmasq.service.
May 03 22:38:08 volumio systemd[1]: Stopped dhcpd.service.
May 03 22:38:08 volumio systemd[1]: Stopping hotspot.service...
May 03 22:38:13 volumio hotspot[1524]: Killing Hostapd
May 03 22:38:13 volumio sudo[1526]: root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/killall hostapd
May 03 22:38:13 volumio sudo[1526]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:38:13 volumio sudo[1526]: pam_unix(sudo:session): session closed for user root
May 03 22:38:13 volumio hotspot[1524]: Killing Dhcpd
May 03 22:38:15 volumio kernel: brcmfmac: brcmf_cfg80211_del_station: SCB_DEAUTHENTICATE_FOR_REASON failed -52
May 03 22:38:18 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: SET SSID error (-52)
May 03 22:38:20 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: BRCMF_C_DOWN error -52
May 03 22:38:22 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: setting AP mode failed -52
May 03 22:38:24 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: setting INFRA mode failed -52
May 03 22:38:26 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: restoring REGULATORY setting failed -52
May 03 22:38:28 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: BRCMF_C_UP error -52
May 03 22:38:30 volumio kernel: brcmfmac: brcmf_set_mpc: fail to set mpc
May 03 22:38:32 volumio dhcpcd[664]: wlan0: carrier lost
May 03 22:38:32 volumio netplugd[1055]: wlan0: state ACTIVE flags 0x00011043 UP,BROADCAST,RUNNING,MULTICAST,10000 -> 0x00001003 UP,BROADCAST,MULTICAST
May 03 22:38:32 volumio netplugd[1536]: /etc/netplug/netplug wlan0 out -> pid 1536
May 03 22:38:32 volumio sudo[1534]: root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/killall dhcpd
May 03 22:38:32 volumio systemd[1]: Stopping Wireless Services...
May 03 22:38:32 volumio sudo[1534]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:38:32 volumio systemd[1]: Starting Wireless Services...
May 03 22:38:32 volumio sudo[1534]: pam_unix(sudo:session): session closed for user root
May 03 22:38:32 volumio systemd[1]: hotspot.service: control process exited, code=exited status=1
May 03 22:38:32 volumio hotspot[1524]: dhcpd: no process found
May 03 22:38:32 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: SET SSID error (-52)
May 03 22:38:32 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: BRCMF_C_DOWN error -52
May 03 22:38:32 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: setting AP mode failed -52
May 03 22:38:32 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: setting INFRA mode failed -52
May 03 22:38:32 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: restoring REGULATORY setting failed -52
May 03 22:38:32 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: BRCMF_C_UP error -52
May 03 22:38:32 volumio systemd[1]: Stopped hotspot.service.
May 03 22:38:32 volumio systemd[1]: Unit hotspot.service entered failed state.
May 03 22:38:32 volumio kernel: brcmfmac: brcmf_set_mpc: fail to set mpc
May 03 22:38:32 volumio kernel: brcmfmac: brcmf_cfg80211_change_iface: WLC_SET_INFRA error (-52)
May 03 22:38:32 volumio sudo[1563]: root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iw dev wlan0 set power_save off
May 03 22:38:32 volumio sudo[1563]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:38:32 volumio sudo[1563]: pam_unix(sudo:session): session closed for user root
May 03 22:38:33 volumio wireless.js[1580]: start
May 03 22:38:33 volumio wireless.js[1580]: Cleaning previous...
May 03 22:38:33 volumio systemd[1]: Stopped hotspot.service.
May 03 22:38:33 volumio wireless.js[1580]: stophotspotchild process exited with code 0
May 03 22:38:33 volumio sudo[1589]: root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ip addr flush dev wlan0
May 03 22:38:33 volumio sudo[1589]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:38:33 volumio avahi-daemon[466]: Withdrawing address record for 192.168.211.1 on wlan0.
May 03 22:38:33 volumio avahi-daemon[466]: Leaving mDNS multicast group on interface wlan0.IPv4 with address 192.168.211.1.
May 03 22:38:33 volumio avahi-daemon[466]: Interface wlan0.IPv4 no longer relevant for mDNS.
May 03 22:38:33 volumio sudo[1589]: pam_unix(sudo:session): session closed for user root
May 03 22:38:33 volumio volumio[1057]: info: mDNS: A device disapperared from network
May 03 22:38:33 volumio volumio[1057]: info: mDNS: Device volumio disapperared from network
May 03 22:38:33 volumio sudo[1597]: root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0 down
May 03 22:38:33 volumio sudo[1597]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:38:35 volumio kernel: brcmfmac: _brcmf_set_multicast_list: Setting mcast_list failed, -52
May 03 22:38:37 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: SET SSID error (-52)
May 03 22:38:39 volumio kernel: brcmfmac: _brcmf_set_multicast_list: Setting allmulti failed, -52
May 03 22:38:41 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: BRCMF_C_DOWN error -52
May 03 22:38:43 volumio kernel: brcmfmac: _brcmf_set_multicast_list: Setting BRCMF_C_SET_PROMISC failed, -52
May 03 22:38:45 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: setting AP mode failed -52
May 03 22:38:47 volumio kernel: brcmfmac: _brcmf_set_multicast_list: Setting mcast_list failed, -52
May 03 22:38:49 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: setting INFRA mode failed -52
May 03 22:38:51 volumio kernel: brcmfmac: _brcmf_set_multicast_list: Setting allmulti failed, -52
May 03 22:38:53 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: restoring REGULATORY setting failed -52
May 03 22:38:55 volumio kernel: brcmfmac: _brcmf_set_multicast_list: Setting BRCMF_C_SET_PROMISC failed, -52
May 03 22:38:57 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: BRCMF_C_UP error -52
May 03 22:38:59 volumio kernel: brcmfmac: brcmf_set_mpc: fail to set mpc
May 03 22:39:01 volumio netplugd[1055]: wlan0: state OUTING flags 0x00001003 UP,BROADCAST,MULTICAST -> 0x00001002 BROADCAST,MULTICAST
May 03 22:39:01 volumio ntpd[537]: Deleting interface #4 wlan0, 192.168.211.1#123, interface stats: received=0, sent=0, dropped=0, active_time=144 secs
May 03 22:39:01 volumio ntpd[537]: peers refreshed
May 03 22:39:01 volumio sudo[1597]: pam_unix(sudo:session): session closed for user root
May 03 22:39:01 volumio wireless.js[1580]: killing: kill `pgrep -f "^/usr/bin/sudo"` || true
May 03 22:39:01 volumio wireless.js[1580]: ifdeconfigchild process exited with code 0
May 03 22:39:01 volumio wireless.js[1580]: killing: kill `pgrep -f "^wpa_supplicant"` || true
May 03 22:39:02 volumio wireless.js[1580]: Stopped aP
May 03 22:39:02 volumio wireless.js[1580]: Start wireless flow
May 03 22:39:02 volumio wireless.js[1580]: Stopped hotspot (if there)..
May 03 22:39:02 volumio sudo[1612]: root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ip addr flush dev wlan0
May 03 22:39:02 volumio sudo[1612]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:02 volumio sudo[1612]: pam_unix(sudo:session): session closed for user root
May 03 22:39:02 volumio sudo[1620]: root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0 down
May 03 22:39:02 volumio sudo[1620]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:02 volumio sudo[1620]: pam_unix(sudo:session): session closed for user root
May 03 22:39:02 volumio wireless.js[1580]: Conf sudo ip addr flush dev wlan0 && sudo ifconfig wlan0 down
May 03 22:39:02 volumio wireless.js[1580]: launching wpa_supplicant args:
May 03 22:39:02 volumio wireless.js[1580]: [ '-d',
May 03 22:39:02 volumio wireless.js[1580]: '-s',
May 03 22:39:02 volumio wireless.js[1580]: '-B',
May 03 22:39:02 volumio wireless.js[1580]: '-Dnl80211,wext',
May 03 22:39:02 volumio wireless.js[1580]: '-c/etc/wpa_supplicant/wpa_supplicant.conf',
May 03 22:39:02 volumio wireless.js[1580]: '-iwlan0' ]
May 03 22:39:02 volumio wpa_supplicant[1628]: wpa_supplicant v2.3
May 03 22:39:02 volumio wpa_supplicant[1628]: random: Trying to read entropy from /dev/random
May 03 22:39:02 volumio wpa_supplicant[1628]: Successfully initialized wpa_supplicant
May 03 22:39:02 volumio wpa_supplicant[1628]: Initializing interface 'wlan0' conf '/etc/wpa_supplicant/wpa_supplicant.conf' driver 'nl80211,wext' ctrl_interface 'N/A' bridge 'N/A'
May 03 22:39:02 volumio wpa_supplicant[1628]: Configuration file '/etc/wpa_supplicant/wpa_supplicant.conf' -> '/etc/wpa_supplicant/wpa_supplicant.conf'
May 03 22:39:02 volumio wpa_supplicant[1628]: Reading configuration file '/etc/wpa_supplicant/wpa_supplicant.conf'
May 03 22:39:02 volumio wpa_supplicant[1628]: rfkill: initial event: idx=0 type=1 op=0 soft=0 hard=0
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Using driver-based roaming
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: TDLS supported
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Supported cipher 00-0f-ac:1
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Supported cipher 00-0f-ac:5
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Supported cipher 00-0f-ac:2
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Supported cipher 00-0f-ac:4
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Supported cipher 00-0f-ac:6
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Using driver-based off-channel TX
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Supported vendor command: vendor_id=0x1018 subcmd=1
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Use separate P2P group interface (driver advertised support)
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Enable multi-channel concurrent (driver advertised support)
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: interface wlan0 in phy phy0
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Set mode ifindex 3 iftype 3 (AP)
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Setup AP(wlan0) - device_ap_sme=0 use_monitor=1
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Create interface iftype 6 (MONITOR)
May 03 22:39:02 volumio wpa_supplicant[1628]: Failed to create interface mon.wlan0: -95 (Operation not supported)
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Driver does not support monitor interface type - try to run without it
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Enable Probe Request reporting nl_preq=0x55f75c50
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Register frame type=0x40 (WLAN_FC_STYPE_PROBE_REQ) nl_handle=0x55f75c50 match=
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Register frame command failed (type=64): ret=-22 (Invalid argument)
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Register frame match - hexdump(len=0): [NULL]
May 03 22:39:02 volumio wpa_supplicant[1628]: nl80211: Failed to enable Probe Request frame reporting in AP mode
May 03 22:39:02 volumio wireless.js[1580]: wpasupp undefined
May 03 22:39:02 volumio wireless.js[1580]: DHCP IP
May 03 22:39:02 volumio wireless.js[1580]: launching /usr/bin/sudo args:
May 03 22:39:02 volumio wireless.js[1580]: [ '/sbin/dhcpcd' ]
May 03 22:39:02 volumio wireless.js[1580]: Start ap
May 03 22:39:02 volumio wireless.js[1580]: ifdeconfigchild process exited with code 0
May 03 22:39:03 volumio wireless.js[1580]: trying...
May 03 22:39:04 volumio netplugd[1055]: wlan0: state DOWNANDOUT flags 0x00001002 BROADCAST,MULTICAST -> 0x00001003 UP,BROADCAST,MULTICAST
May 03 22:39:04 volumio netplugd[1055]: wlan0: unexpected state DOWNANDOUT for UP
May 03 22:39:04 volumio wpa_supplicant[1628]: netlink: Operstate: ifindex=3 linkmode=1 (userspace-control), operstate=5 (IF_OPER_DORMANT)
May 03 22:39:04 volumio wpa_supplicant[1628]: nl80211: driver param='(null)'
May 03 22:39:04 volumio wpa_supplicant[1628]: Add interface wlan0 to a new radio phy0
May 03 22:39:04 volumio wpa_supplicant[1628]: nl80211: Regulatory information - country=00
May 03 22:39:04 volumio wpa_supplicant[1628]: nl80211: 2402-2472 @ 40 MHz 20 mBm
May 03 22:39:04 volumio wpa_supplicant[1628]: nl80211: 2457-2482 @ 20 MHz 20 mBm (no IR)
May 03 22:39:04 volumio wpa_supplicant[1628]: nl80211: 2474-2494 @ 20 MHz 20 mBm (no OFDM) (no IR)
May 03 22:39:04 volumio wpa_supplicant[1628]: nl80211: 5170-5250 @ 80 MHz 20 mBm (no IR)
May 03 22:39:04 volumio wpa_supplicant[1628]: nl80211: 5250-5330 @ 80 MHz 20 mBm (DFS) (no IR)
May 03 22:39:04 volumio wpa_supplicant[1628]: nl80211: 5490-5730 @ 160 MHz 20 mBm (DFS) (no IR)
May 03 22:39:04 volumio wpa_supplicant[1628]: nl80211: 5735-5835 @ 80 MHz 20 mBm (no IR)
May 03 22:39:04 volumio wpa_supplicant[1628]: nl80211: 57240-63720 @ 2160 MHz 0 mBm
May 03 22:39:04 volumio wpa_supplicant[1628]: nl80211: Added 802.11b mode based on 802.11g information
May 03 22:39:04 volumio wpa_supplicant[1628]: nl80211: Do not indicate P2P_DEVICE support (p2p_device=1 driver param not specified)
May 03 22:39:04 volumio sudo[1629]: root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/dhcpcd
May 03 22:39:04 volumio sudo[1631]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:04 volumio sudo[1631]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:04 volumio sudo[1629]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:04 volumio kernel: brcmfmac: brcmf_proto_bcdc_query_dcmd: brcmf_proto_bcdc_msg failed w/status -110
May 03 22:39:04 volumio dhcpcd[1638]: dhcpcd already running on pid 664 (/var/run/dhcpcd.pid)
May 03 22:39:04 volumio sudo[1631]: pam_unix(sudo:session): session closed for user root
May 03 22:39:04 volumio sudo[1629]: pam_unix(sudo:session): session closed for user root
May 03 22:39:04 volumio wireless.js[1580]: dhclientstderr: dhcpcd[1638]: dhcpcd already running on pid 664 (/var/run/dhcpcd.pid)
May 03 22:39:04 volumio wireless.js[1580]: dhclientchild process exited with code 1
May 03 22:39:04 volumio wpa_supplicant[1628]: wlan0: Own MAC address: b8:27:eb:c0:2a:65
May 03 22:39:04 volumio wpa_supplicant[1628]: wpa_driver_nl80211_set_key: ifindex=3 (wlan0) alg=0 addr=(nil) key_idx=0 set_tx=0 seq_len=0 key_len=0
May 03 22:39:05 volumio wireless.js[1580]: trying...
May 03 22:39:06 volumio kernel: brcmfmac: _brcmf_set_multicast_list: Setting mcast_list failed, -52
May 03 22:39:08 volumio kernel: brcmfmac: _brcmf_set_multicast_list: Setting allmulti failed, -52
May 03 22:39:10 volumio kernel: brcmfmac: _brcmf_set_multicast_list: Setting BRCMF_C_SET_PROMISC failed, -52
May 03 22:39:12 volumio wpa_supplicant[1628]: nl80211: set_key failed; err=-52 Invalid exchange)
May 03 22:39:12 volumio wpa_supplicant[1628]: wpa_driver_nl80211_set_key: ifindex=3 (wlan0) alg=0 addr=(nil) key_idx=1 set_tx=0 seq_len=0 key_len=0
May 03 22:39:12 volumio kernel: brcmfmac: send_key_to_dongle: wsec_key error (-52)
May 03 22:39:14 volumio wpa_supplicant[1628]: nl80211: set_key failed; err=-52 Invalid exchange)
May 03 22:39:14 volumio wpa_supplicant[1628]: wpa_driver_nl80211_set_key: ifindex=3 (wlan0) alg=0 addr=(nil) key_idx=2 set_tx=0 seq_len=0 key_len=0
May 03 22:39:14 volumio sudo[1647]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:14 volumio kernel: brcmfmac: send_key_to_dongle: wsec_key error (-52)
May 03 22:39:14 volumio sudo[1647]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:16 volumio wpa_supplicant[1628]: nl80211: set_key failed; err=-52 Invalid exchange)
May 03 22:39:16 volumio wpa_supplicant[1628]: wpa_driver_nl80211_set_key: ifindex=3 (wlan0) alg=0 addr=(nil) key_idx=3 set_tx=0 seq_len=0 key_len=0
May 03 22:39:16 volumio sudo[1647]: pam_unix(sudo:session): session closed for user root
May 03 22:39:16 volumio kernel: brcmfmac: send_key_to_dongle: wsec_key error (-52)
May 03 22:39:17 volumio wireless.js[1580]: trying...
May 03 22:39:18 volumio kernel: brcmfmac: _brcmf_set_multicast_list: Setting mcast_list failed, -52
May 03 22:39:20 volumio kernel: brcmfmac: _brcmf_set_multicast_list: Setting allmulti failed, -52
May 03 22:39:22 volumio kernel: brcmfmac: _brcmf_set_multicast_list: Setting BRCMF_C_SET_PROMISC failed, -52
May 03 22:39:24 volumio wpa_supplicant[1628]: nl80211: set_key failed; err=-52 Invalid exchange)
May 03 22:39:24 volumio wpa_supplicant[1628]: wpa_driver_nl80211_set_key: ifindex=3 (wlan0) alg=0 addr=(nil) key_idx=4 set_tx=0 seq_len=0 key_len=0
May 03 22:39:24 volumio wpa_supplicant[1628]: nl80211: set_key failed; err=-22 Invalid argument)
May 03 22:39:24 volumio wpa_supplicant[1628]: wpa_driver_nl80211_set_key: ifindex=3 (wlan0) alg=0 addr=(nil) key_idx=5 set_tx=0 seq_len=0 key_len=0
May 03 22:39:24 volumio wpa_supplicant[1628]: nl80211: set_key failed; err=-22 Invalid argument)
May 03 22:39:24 volumio wpa_supplicant[1628]: wlan0: RSN: flushing PMKID list in the driver
May 03 22:39:24 volumio wpa_supplicant[1628]: nl80211: Flush PMKIDs
May 03 22:39:24 volumio wpa_supplicant[1628]: wlan0: State: DISCONNECTED -> INACTIVE
May 03 22:39:24 volumio sudo[1657]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:24 volumio kernel: brcmfmac: send_key_to_dongle: wsec_key error (-52)
May 03 22:39:24 volumio sudo[1657]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:24 volumio sudo[1657]: pam_unix(sudo:session): session closed for user root
May 03 22:39:24 volumio wpa_supplicant[1628]: TDLS: TDLS operation supported by driver
May 03 22:39:24 volumio wpa_supplicant[1628]: TDLS: Driver uses internal link setup
May 03 22:39:24 volumio wpa_supplicant[1628]: wlan0: WPS: UUID based on MAC address: 9bfbd413-9345-5c04-b128-84ca182b4930
May 03 22:39:24 volumio wpa_supplicant[1628]: EAPOL: SUPP_PAE entering state DISCONNECTED
May 03 22:39:24 volumio wpa_supplicant[1628]: EAPOL: Supplicant port status: Unauthorized
May 03 22:39:24 volumio wpa_supplicant[1628]: nl80211: Skip set_supp_port(unauthorized) while not associated
May 03 22:39:24 volumio wpa_supplicant[1628]: EAPOL: KEY_RX entering state NO_KEY_RECEIVE
May 03 22:39:24 volumio wpa_supplicant[1628]: EAPOL: SUPP_BE entering state INITIALIZE
May 03 22:39:24 volumio wpa_supplicant[1628]: EAP: EAP entering state DISABLED
May 03 22:39:24 volumio wpa_supplicant[1628]: P2P: Add operating class 81
May 03 22:39:24 volumio wpa_supplicant[1628]: P2P: Channels - hexdump(len=11): 01 02 03 04 05 06 07 08 09 0a 0b
May 03 22:39:24 volumio wpa_supplicant[1628]: P2P: Own listen channel: 81:11
May 03 22:39:24 volumio wpa_supplicant[1628]: P2P: Random operating channel: 81:1
May 03 22:39:24 volumio wpa_supplicant[1628]: P2P: initialized
May 03 22:39:24 volumio wpa_supplicant[1628]: P2P: channels: 81:1,2,3,4,5,6,7,8,9,10,11
May 03 22:39:24 volumio wpa_supplicant[1628]: P2P: cli_channels:
May 03 22:39:24 volumio wpa_supplicant[1628]: wlan0: Added interface wlan0
May 03 22:39:24 volumio wpa_supplicant[1628]: wlan0: State: INACTIVE -> DISCONNECTED
May 03 22:39:24 volumio wpa_supplicant[1628]: nl80211: Set wlan0 operstate 0->0 (DORMANT)
May 03 22:39:24 volumio wpa_supplicant[1628]: netlink: Operstate: ifindex=3 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
May 03 22:39:24 volumio wpa_supplicant[1628]: Daemonize..
May 03 22:39:24 volumio wpa_supplicant[1665]: random: Got 20/20 bytes from /dev/random
May 03 22:39:24 volumio wpa_supplicant[1665]: RTM_NEWLINK: ifi_index=3 ifname=wlan0 operstate=2 linkmode=0 ifi_family=0 ifi_flags=0x1003 ([UP])
May 03 22:39:24 volumio wpa_supplicant[1665]: RTM_NEWLINK: ifi_index=3 ifname=wlan0 operstate=2 linkmode=1 ifi_family=0 ifi_flags=0x1003 ([UP])
May 03 22:39:24 volumio wireless.js[1580]: wpa supplicantchild process exited with code 0
May 03 22:39:25 volumio wireless.js[1580]: trying...
May 03 22:39:25 volumio sudo[1667]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:25 volumio wpa_supplicant[1665]: EAPOL: disable timer tick
May 03 22:39:25 volumio sudo[1667]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:25 volumio sudo[1667]: pam_unix(sudo:session): session closed for user root
May 03 22:39:26 volumio wireless.js[1580]: trying...
May 03 22:39:26 volumio sudo[1676]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:26 volumio sudo[1676]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:26 volumio sudo[1676]: pam_unix(sudo:session): session closed for user root
May 03 22:39:27 volumio wireless.js[1580]: trying...
May 03 22:39:27 volumio sudo[1685]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:27 volumio sudo[1685]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:27 volumio sudo[1685]: pam_unix(sudo:session): session closed for user root
May 03 22:39:28 volumio wireless.js[1580]: trying...
May 03 22:39:28 volumio sudo[1694]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:28 volumio sudo[1694]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:28 volumio sudo[1694]: pam_unix(sudo:session): session closed for user root
May 03 22:39:29 volumio wireless.js[1580]: trying...
May 03 22:39:29 volumio sudo[1704]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:29 volumio sudo[1704]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:29 volumio sudo[1704]: pam_unix(sudo:session): session closed for user root
May 03 22:39:30 volumio wireless.js[1580]: trying...
May 03 22:39:30 volumio sudo[1714]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:30 volumio sudo[1714]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:30 volumio sudo[1714]: pam_unix(sudo:session): session closed for user root
May 03 22:39:31 volumio wireless.js[1580]: trying...
May 03 22:39:31 volumio sudo[1723]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:31 volumio sudo[1723]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:31 volumio sudo[1723]: pam_unix(sudo:session): session closed for user root
May 03 22:39:32 volumio wireless.js[1580]: trying...
May 03 22:39:32 volumio sudo[1732]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:32 volumio sudo[1732]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:32 volumio sudo[1732]: pam_unix(sudo:session): session closed for user root
May 03 22:39:33 volumio wireless.js[1580]: trying...
May 03 22:39:33 volumio sudo[1741]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:33 volumio sudo[1741]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:33 volumio sudo[1741]: pam_unix(sudo:session): session closed for user root
May 03 22:39:34 volumio wireless.js[1580]: trying...
May 03 22:39:34 volumio sudo[1750]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:34 volumio sudo[1750]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:34 volumio sudo[1750]: pam_unix(sudo:session): session closed for user root
May 03 22:39:35 volumio wireless.js[1580]: trying...
May 03 22:39:35 volumio sudo[1759]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:35 volumio sudo[1759]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:35 volumio sudo[1759]: pam_unix(sudo:session): session closed for user root
May 03 22:39:36 volumio wireless.js[1580]: trying...
May 03 22:39:36 volumio sudo[1768]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:36 volumio sudo[1768]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:36 volumio sudo[1768]: pam_unix(sudo:session): session closed for user root
May 03 22:39:37 volumio wireless.js[1580]: trying...
May 03 22:39:37 volumio sudo[1777]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:37 volumio sudo[1777]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:37 volumio sudo[1777]: pam_unix(sudo:session): session closed for user root
May 03 22:39:38 volumio wireless.js[1580]: trying...
May 03 22:39:38 volumio sudo[1786]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:38 volumio sudo[1786]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:38 volumio sudo[1786]: pam_unix(sudo:session): session closed for user root
May 03 22:39:39 volumio wireless.js[1580]: trying...
May 03 22:39:39 volumio sudo[1796]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:39 volumio sudo[1796]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:39 volumio sudo[1796]: pam_unix(sudo:session): session closed for user root
May 03 22:39:40 volumio wireless.js[1580]: trying...
May 03 22:39:40 volumio sudo[1805]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:40 volumio sudo[1805]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:40 volumio sudo[1805]: pam_unix(sudo:session): session closed for user root
May 03 22:39:41 volumio wireless.js[1580]: trying...
May 03 22:39:41 volumio sudo[1814]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwgetid -r
May 03 22:39:41 volumio sudo[1814]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:39:41 volumio sudo[1814]: pam_unix(sudo:session): session closed for user root
May 03 22:39:42 volumio wireless.js[1580]: Overtime, starting plan B
May 03 22:39:42 volumio wireless.js[1580]: killing: kill `pgrep -f "^/usr/bin/sudo"` || true
May 03 22:39:42 volumio wireless.js[1580]: killing: kill `pgrep -f "^wpa_supplicant"` || true
May 03 22:39:42 volumio wpa_supplicant[1665]: wlan0: Removing interface wlan0
May 03 22:39:42 volumio wpa_supplicant[1665]: wlan0: Request to deauthenticate - bssid=00:00:00:00:00:00 pending_bssid=00:00:00:00:00:00 reason=3 state=DISCONNECTED
May 03 22:39:42 volumio wpa_supplicant[1665]: TDLS: Tear down peers
May 03 22:39:42 volumio wpa_supplicant[1665]: wlan0: State: DISCONNECTED -> DISCONNECTED
May 03 22:39:42 volumio wpa_supplicant[1665]: nl80211: Set wlan0 operstate 0->0 (DORMANT)
May 03 22:39:42 volumio wpa_supplicant[1665]: netlink: Operstate: ifindex=3 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
May 03 22:39:42 volumio wpa_supplicant[1665]: EAPOL: External notification - portEnabled=0
May 03 22:39:42 volumio wpa_supplicant[1665]: EAPOL: External notification - portValid=0
May 03 22:39:42 volumio wpa_supplicant[1665]: wlan0: Cancelling delayed sched scan
May 03 22:39:42 volumio wpa_supplicant[1665]: wlan0: Cancelling scan request
May 03 22:39:42 volumio wpa_supplicant[1665]: wlan0: Cancelling authentication timeout
May 03 22:39:42 volumio wpa_supplicant[1665]: wlan0: P2P: Disable P2P since removing the management interface is being removed
May 03 22:39:42 volumio wpa_supplicant[1665]: P2P: Stopping find
May 03 22:39:42 volumio wpa_supplicant[1665]: P2P: Clear timeout (state=IDLE)
May 03 22:39:42 volumio wpa_supplicant[1665]: P2P: State IDLE -> IDLE
May 03 22:39:42 volumio wpa_supplicant[1665]: Remove interface wlan0 from radio phy0
May 03 22:39:42 volumio wpa_supplicant[1665]: Remove radio phy0
May 03 22:39:42 volumio wpa_supplicant[1665]: nl80211: Remove monitor interface: refcount=0
May 03 22:39:42 volumio wpa_supplicant[1665]: nl80211: Remove beacon (ifindex=3)
May 03 22:39:45 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: SET SSID error (-52)
May 03 22:39:45 volumio systemd[1]: Stopped hotspot.service.
May 03 22:39:45 volumio wireless.js[1580]: stophotspotchild process exited with code 0
May 03 22:39:47 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: BRCMF_C_DOWN error -52
May 03 22:39:49 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: setting AP mode failed -52
May 03 22:39:51 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: setting INFRA mode failed -52
May 03 22:39:53 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: restoring REGULATORY setting failed -52
May 03 22:39:55 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: BRCMF_C_UP error -52
May 03 22:39:57 volumio kernel: brcmfmac: brcmf_set_mpc: fail to set mpc
May 03 22:39:59 volumio wpa_supplicant[1665]: netlink: Operstate: ifindex=3 linkmode=0 (kernel-control), operstate=6 (IF_OPER_UP)
May 03 22:40:01 volumio sudo[1829]: root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ip addr flush dev wlan0
May 03 22:40:01 volumio kernel: brcmfmac: brcmf_proto_bcdc_query_dcmd: brcmf_proto_bcdc_msg failed w/status -110
May 03 22:40:01 volumio kernel: brcmfmac: brcmf_cfg80211_get_tx_power: error (-52)
May 03 22:40:01 volumio sudo[1829]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 03 22:40:02 volumio systemd[1]: wireless.service start operation timed out. Terminating.
May 03 22:40:02 volumio systemd[1]: Failed to start Wireless Services.
May 03 22:40:02 volumio systemd[1]: Unit wireless.service entered failed state.
May 03 22:40:02 volumio sudo[1498]: pam_unix(sudo:session): session closed for user root
May 03 22:40:03 volumio kernel: brcmfmac: _brcmf_set_multicast_list: Setting mcast_list failed, -52
May 03 22:40:05 volumio kernel: brcmfmac: _brcmf_set_multicast_list: Setting allmulti failed, -52
May 03 22:40:07 volumio kernel: brcmfmac: _brcmf_set_multicast_list: Setting BRCMF_C_SET_PROMISC failed, -52
May 03 22:40:09 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: SET SSID error (-52)
May 03 22:40:11 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: BRCMF_C_DOWN error -52
May 03 22:40:12 volumio volumio[1057]: info: CoreCommandRouter::executeOnPlugin: upnp , onRestart
May 03 22:40:13 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: setting AP mode failed -52
May 03 22:40:15 volumio kernel: brcmfmac: brcmf_cfg80211_stop_ap: setting INFRA mode failed -52


Seems something terribly wrong, but can't understand what

**Comment by macmpi** [comment]
Can you try with 2.129 which was the last known-good release?
Then can you put 2.141 squash onto that same SD and wipe all data? This would use exact same 2.129 firmware & overlays with 2.141 (I assume those 2 versions have unchanged initramfs, not sure it's changed in 2.156 image)

**Comment by volumio** [comment]
Yep, I'll try that...

**Comment by volumio** [comment]
As weird as it might sound, I got 3 fault PIs...
Tried with the 4th one, and it just works... No issue whatsoever.
I think tomorrow we should start a thread on the forum to understand how many people have broken pi's wifi...

**Comment by nilsbecker** [comment]
i tried again. with a different non-volumio sd card i can still use the wifi. so on my Pi3, the volumio update did not brick the internal wifi. it's only nonfunctional

**Comment by macmpi** [comment]
I'm a bit confused, not sure I understand:
Are the 3 failing with 2.129 too, or is fail only with 2.141 and later?
Is the 4th one working with plain 2.141 / 2.129 ?

This kind of reminds-me of some older articles read about some tiny HW differences across some batches of Pi3 which required updated firmware files (can't find the exact reference of these articles right now).
Current 4.4.9 build does a bit of mix&match of firmware files to accommodate old kernel with more recent devices & related dtbs: maybe we touched some limits with the recently-created images.

Do you have same issue if you build image with the 4.9.25 (and same Volumio2 commit references)?

**Comment by macmpi** [comment]
@nilsbecker did you try with a re-imaged Volumio SD (not OTA updated)?
Which Volumio version was working fine on your device before?

**Comment by nilsbecker** [comment]
no, haven't had the time to re-flash. the previously working version was 2.129.

**Comment by macmpi** [comment]
@volumio it turns-out last week stable branch of https://github.com/Hexxeh/rpi-firmware/ moved to 4.9.24!...
so we probably have big mixed bag of kernel / firmware files in images built since!...

**Comment by volumio** [comment]
@macmpi is there a way to download an exact firmware like we do with the kernel? 
aka using the commit hash?

**Comment by macmpi** [comment]
Probably, I'll look at it.
In the meantime, to confirm, can you try keeping all `/boot` files from 2.129  and just replace squash with 2.141 and check it works on your devices?

**Comment by volumio** [comment]
sure, give me few hours and I'll do that . Now my wireless is working with 2.156

**Comment by macmpi** [comment]
> Now my wireless is working with 2.156

doing what?
Mixed stuff will produce unpredictable results anyway: now we see it with wireless, but DAC support is going to be terrible too...

**Comment by volumio** [comment]
Internal wireless of PI3 is working. 
I'll do the checks, then we will stick with a firmware version once you find it, what do you think

**Comment by macmpi** [comment]
Yes: I'm investigating about firmware revisions.
So you confirm the recent udev rules changes are not suspected anymore?

**Comment by volumio** [comment]
Yes, we can rule out the udev rule change. 
Two things that could interfere are: 
- The GPIO PR (we're changing permissions here and there, including SPI and UART, used by wifi)
- The 2 commits on hotspot.sh

**Comment by macmpi** [comment]
Can you check with this https://github.com/volumio/Build/pull/191 ?
This should fix the firmware discrepancies (BTW PiZero W users were also complaining, probably same root cause)

**Comment by nilsbecker** [comment]
i could test flash or opgrade something if desired...

**Comment by macmpi** [comment]
@nilsbecker you may refer to [this](https://volumio.org/forum/trouble-connecting-zero-home-wifi-t6471-10.html#p32330) for an interim fix, until a new version is available.

**Comment by nilsbecker** [comment]
thanks @macmpi .

**Comment by volumio** [comment]
Tried with newer kernel, nope... wifi still broken... And furthermore, it seems quite a common problem

**Comment by macmpi** [comment]
So you still have 1 Pi3 working, and 3 not working?
Can you try this under console after boot:
```
sudo modprobe -r brcmfmac
sudo modprobe brcmfmac
```
does it help?

**Comment by volumio** [comment]
Nope.. no wifi if I do ifconfig -a

**Comment by macmpi** [comment]
@nilsbecker did it fix your problem?
If so, can you please close this issue?
Thanks.

**Comment by nilsbecker** [comment]
ok, i updated to 2.163. i had to do the `modprobe brcmfmac` game above, then i got a working wireless connection back. great!

**Comment by macmpi** [comment]
@nilsbecker : very interesting thanks.
So without driver unload/reload your Pi3 can not operate with onboard wifi?
Do you have to do it at each reboot then?

**Comment by nilsbecker** [comment]
rebooting now...

**Comment by macmpi** [comment]
...and also...how did you "upgrade": reflash or OTA?

**Comment by nilsbecker** [comment]
OTA

**Comment by macmpi** [comment]
OTA won't change firmware files I'm afraid, so you may still have the original issue.
Can you reflash with 2.163?

**Comment by nilsbecker** [comment]
yes, i spoke too soon, after a new reboot it's not working. interestingly on the first boot after OTA it did. hmm. so i'll have to flash.

**Comment by nilsbecker** [comment]
is there a way to preserve the volumio home dir and other installed packages?

**Comment by macmpi** [comment]
you can save/restore in a hack-ish manner yes (for now): look at [this](https://github.com/volumio/Volumio2/issues/1048#issuecomment-288077276)

**Comment by nilsbecker** [comment]
ok, i flashed 2.163 and was able to get a wireless connection working. atm i have problems with the web interface stalling after a while, but this is not related to getting a wireless connection, which i confirm works.
