### ISSUE TITLE
RC2 [HOTFIX] deleted all my files

### ISSUE THREAD

**Issue by xarath** [volumio/Volumio2#524]
Fresh install of RC2 [HOTFIX].  Mounted an NFS drive through the GUI and tried playing some music.  Then, I cleared the queue (and it wouldn't clear).  Files were no longer listed under NAS and I looked on the drive itself and every files were gone but the ones that were in the queue.  I had to restore from backups.  I would strongly advise anyone to mount read only.

**Comment by jomo** [comment]
Likely relevant commit: 1d536ec6d75d894f7333cf1e71649e0abcaa9ed7

If I read that code correctly, it tries to `unmount` the NAS and if that fails, it just tries deleting it using `rm -rf`.

**Comment by jomo** [comment]
nvm, it actually does that only if `umnount` results in `error === null`.

**Comment by jomo** [comment]
I'm not sure if `rm -rf` was the culprit in this case (code looks good IMO), but #525 makes sure at least that can't happen.

**Comment by volumio** [comment]
Oh bad thing... I prevented that by mounting read only, but I realize now that I did only for CIFS. Do you know how can we add the ro option for nfs?

**Comment by xarath** [comment]
By adding ro option in /etc/fstab. Here is the relevant line:
192.168.1.5:/data3/music	/mnt/NAS/Music2	nfs4	_netdev,auto,ro	0	0

**Comment by volumio** [comment]
Should be solved with 
https://github.com/volumio/Volumio2/commit/d64213f9c050bb05542a2a4ae53656ecd2f056d1

Is anyone able to test by doing 

cd /volumio
git pull
killall node 

Please let me know

**Comment by xipmix** [comment]
I don't think d64213f is the right fix, because it uses options that are not supported for NFS mounts.
I noticed this back in volumio1 but never figured out how to report it concisely. I think if you set the base options as "ro,noauto"  it will work better.
`
fsopts = credentials + "ro,noauto";
`
`
if (options) {
  fsopts = fsopts + "," + options;
}
`

You might want to try 'bg' as well so it will keep retrying but I'm not sure how well supported it is.

**Comment by xipmix** [comment]
Also you may want to be explicit that you want 'soft' mounts `"ro,soft,noauto"`, which should be ok as long as the mount is readonly. If options contains 'rw' that might override and open the way to possible file corruption on the NAS end.

**Comment by volumio** [comment]
Ok, added with 
https://github.com/volumio/Volumio2/commit/4a30ebaca97fb2e20be9a15b497bca17de2b0466

Could you please try if that works ok?

**Comment by xipmix** [comment]
I tried it just now. volumio does not mount the NAS but a manual mount command works. Where should I look in the logs please?

**Comment by xipmix** [comment]
Found it. journalctl -p 7 shows me the mount attempt:
 `mount -t nfs -o undefinedro,soft,noauto ...`

**Comment by xipmix** [comment]
Fixed by setting `credentials = ''` in the NFS case.

**Comment by volumio** [comment]
Fixed here https://github.com/volumio/Volumio2/commit/c3908e504f7c3d333d1a671db206d031283406fb

Could you try?

**Comment by xipmix** [comment]
Shortly after I ran 'killall node' I got the startup sound and 'mount|grep nfs' showed the right thing.
But I was hasty and typed reboot to check that it was really working (I'd done a manual mount before). systemd made me wait for mpd to finish with the filesystem (around 1 minute), but eventually the reboot went ahead and voila the NAS filesystem is mounted 'ro'.

**Comment by volumio** [comment]
Well done! Thank you very much! This was really urgent to solve...

**Comment by xipmix** [comment]
Just to cover this since it was mentioned by @xarath, the `_netdev` option will not hurt but is probably not needed now since systemd knows about NFS mounts. 

See for example http://codingberg.com/linux/systemd_when_to_use_netdev_mount_option

**Comment by jomo** [comment]
@volumio it's still not clear why the files were deleted in the first place, is it?

**Comment by volumio** [comment]
Yes, we know why. NFS was not mounted Read only, and when the share was deleted, mpd was updating the db. So the share was not unmounteed, but the folder was deleted. 
With this fix it won't happen again, since the mount will be read only

**Comment by jomo** [comment]
Shouldn't `unmount` return an error when it fails (so `rm -rf` would not run)?
Is this due to the lazy `unmount -l`? The man page says the filesystem is detached immediately though.

**Comment by volumio** [comment]
Yes, it should do like that ... But if mpd is somehow scanning, this might take a while... Or at least this is my explanation...
