### ISSUE TITLE
NAS size error: NaN when path has spaces

### ISSUE THREAD

**Issue by macmpi** [volumio/Volumio2#856]
There seem to be a nasty bug in NAS shares size extraction [in here](https://github.com/volumio/Volumio2/blob/master/app/plugins/system_controller/networkfs/index.js#L523).
Indeed when share path has spaces in it, then `awk` gets mixed-up, and does not returns the proper column!...
Following size calculation is then altered and may end-up with NaN, which is what got displayed in UI.

**Comment by xipmix** [comment]
This should fix the issue with spaces in the mountpoint
```
- var cmd="df -BM "+mountpoint+" | awk '{print $3}'";
+ var cmd="df -BM --output=used '"+mountpoint+"' | tail -1 | awk '{print $1}'";
```
but ... does the code (in current git) that sets up shares allow spaces in the name?

**Comment by macmpi** [comment]
Thanks a lot: will try that.
I was not referring to spaces in the `mountpoint` name per say, but spaces within the mounted server path (like `192.168.3.200:Multimedia/MUSIC/iTunes Master/iTunes Media/Music` fairly common in iTunes for instance).
Paths with spaces seem supported (changelog in recent 2.0.29 `Fix share with spaces` makes it even more explicit).

**Comment by volumio** [comment]
Good tip! I'll try it now

**Comment by 2lepus** [comment]
When the mounted folder has no spaces but the subfolders have, then you get 0.00MB instead

**Comment by 2lepus** [comment]
Ok, though I deleted that mount and mounted it again I still get 0.00MB or something smaller than the real size.
(with 2.0.29)
![screen](https://cloud.githubusercontent.com/assets/23573316/20455528/5d734a9a-ae5e-11e6-8798-4e0afd68e58d.png)

**Comment by xipmix** [comment]
> I was not referring to spaces in the mountpoint name per say, but spaces within the mounted server path (like 192.168.3.200:Multimedia/MUSIC/iTunes Master/iTunes Media/Music fairly common in iTunes for instance).

Ah, yes. I was worried about that too. Using ```--output=used``` works around that by not printing the paths at all.

**Comment by macmpi** [comment]
With https://github.com/volumio/Volumio2/pull/879 closed, is this original issue meant to be fixed as a consequence of https://github.com/volumio/Volumio2/pull/1010 commit, or is this issue is still waiting for pending resolution (and updated PR)?
Thanks to close the issue if now fixed.

**Comment by xipmix** [comment]
I plan to submit a new PR that improves the df call but drops the rest of it, I'm guessing there was some discomfort with the number formatting stuff.
